# Document:
# http://simiki.org/docs/configuration.html

url: http://mpmsimo.github.io
title: Wiki - Michael Simo
keywords: wiki, markdown, linux, python, sysadmin, openstack
description: "Michael Simo's personal wiki page which covers a variety of topics including Linux, Python, and OpenStack." 
author: Michael Simo
